language: rust
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failure:
    - rust: nightly
  fast_finish: true
  include:
    - name: Build
      script: cd src && cargo build --all

    - name: Test
      script: cargo test --verbose --all

cache: cargo
