language: rust

sudo : required

script:
  - cd src && cargo build --verbose --all
  - cargo test --verbose --all
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failure:
    - rust: nightly
  fast_finish: true
cache: cargo

addons:
  apt:
    packages:
      - libssl-dev


before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi


# Upload code coverage
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi