language: rust
script:
  - cd src && cargo build --verbose --all
  - cd src && cargo test --verbose --all
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failure:
    - rust: nightly
  fast_finish: true
cache: cargo
